[run]
tEnd=0.1
nStepmax=1

initial_conditions=gadget
nOutput=2

[gadget]
# inputFile=/home/cphyc/Documents/prog/yt-data/GadgetDiskGalaxy/snapshot_200.hdf5
# inputFile=/home/cphyc/Documents/prog/genetIC/genetIC/tests/test_26a_gadgethdf_multifile_baryons/test.hdf5
# inputFile=/home/cphyc/tmp/snapshot_200.hdf5
inputFile=/home/cphyc/tmp/analytical.hdf5

[particles]
# update_density=ParticleUpdate_CIC_density
# density_projected_arrays=star,dark_matter

# [cosmology]
# active=true
# H0=70
# omegam=0.279
# omegal=0.721
# omegab=0.045

[dt]
hydro_cfl=0.8

; [gravity]
; solver=GravitySolver_cg
; CG_eps=1e-2
; 4_Pi_G=3.87783124e-07

[amr]
level_min=4
level_max=5

mass_refine =1e-2
mass_coarsen=0

markers_kernel=RefineCondition_mass

bx=8
by=8
bz=8

load_balancing_frequency=10
cycle_frequency=5

[mesh]
ndim=3

xmin=0.0
xmax=128

ymin=0.0
ymax=128

zmin=0.0
zmax=128

boundary_type_xmin=periodic
boundary_type_xmax=periodic

boundary_type_ymin=periodic
boundary_type_ymax=periodic

boundary_type_zmin=periodic
boundary_type_zmax=periodic

[hydro]
gamma0=1.666
riemann=hllc


[output]
outputDir=./
outputPrefix=blast_3D
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot

[units]
# 1 Mpc/h
length = 1.4285714285714286 kpc
time = 1 Gyr
mass = 2e7 solar_mass