[ini]
convert_units      = true

[run]
tEnd=1e2
output_timeslice=1
nStepmax=10000

initial_conditions=blast,simple_particles

[simple_particles]
npart = 0

[dt]
hydro_cfl=0.8

[amr]
level_min=1
level_max=1

bx=3
by=3
bz=3

[mesh]
ndim=3

[hydro]
gamma0  = 1.666
riemann = hllc
update  = none

[particles]
spawn = ParticleUpdate_star_formation

[star_formation]
# minimum density
density_threshold = 1e-8 proton_mass/cm**3
# maximum temperature
temperature_threshold    = 1e10 K
# star forming efficiency
epsilon_star             = .1

[blast]
density_in=100
density_out=100
pressure_in=1.0
pressure_out=1.0
velocity_in=0.01, 0.02, -0.03
velocity_out=0.01, 0.02, -0.03

[output]
outputDir=./
outputPrefix=star_formation
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot
write_particle_variables=particles/vx,particles/vy,particles/vz,particles/mass
output_real_type=double

[units]
time = 1 Myr
length = 10 pc
density = 1 proton_mass / cm**3
