[ini]
convert_units      = true

[run]
tEnd=15
output_timeslice=1
nStepmax=10000

initial_conditions=blast,simple_particles,uniform

[simple_particles]
attributes = vx,vy,vz,mass,metallicity,birth_time
npart = 3
mass = 1, 1, 1 
metallicity = 1, 1, 1
px = 0.125, 0.375, 0.625
py = 0.5, 0.5, 0.5
pz = 0.5, 0.5, 0.5
# Initialize with:
# - one older than tSNII (will never explode),
# - one that will explode in the first step,
# - one that will explode after tSNII
birth_time = -12, -9.9999999999, 0
vx = 1e-2, 1e-2, 1e-2
vy = 1e-3, 1e-3, 1e-3
vz = 1e-4, 1e-4, 1e-4

[dt]
hydro_cfl=0.8

[amr]
level_min=1
level_max=1

bx=3
by=3
bz=3

[mesh]
ndim=3

[hydro]
gamma0  = 1.666
riemann = hllc
update  = none

[particles]
source_term = ParticleUpdate_feedback

[star_feedback]
# Efficiency of feedback
eta_SNII = 0.1
# Metal yields
yield_SNII = 0.1
# Typical mass of SNII stars
M_SNII = 10 solarmass
# Energy per SNII
E_SNII = 1e51 erg
# Life time of SNII stars
t_SNII = 10 Myr

[blast]
density_in=100
density_out=100
pressure_in=1.0
pressure_out=1.0


[InitialConditions_uniform]
fields = metallicity
# Initialised in conservative form: Z * rho
values = 100

[output]
outputDir=./
outputPrefix=feedback
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,metallicity
write_particle_variables=particles/vx,particles/vy,particles/vz,particles/mass,particles/birth_time,particles/metallicity
output_real_type=double

[units]
time = 1 Myr
length = 10 kpc
mass = 1 solarmass
