[run]
tEnd=0.650
# nStepmax=40
nOutput=1
initial_conditions=uniform,simple_particles
output_frequency=100

[InitialConditions_uniform]
fields=rho,e_tot,rho_vx,rho_vy,rho_vz,e_rad,fx_rad,fy_rad,fz_rad,nH,nHe,xH_I,xH_II,xH2,xHe_I,xHe_II,xHe_III
values=1e0,1e0,0,0,0,0,0,0,0,0.76,0.0599610253335332,1.0,0,0,1.0,0,0

[dt]
dt_kernel=Compute_dt_rad

[simple_particles]
attributes = vx,vy,vz,mass,birth_time
npart = 1
# 4e-4 --> 10 Msun
mass = 4e-4
px = 0.5
py = 0.5
pz = 0.5
birth_time = -0
vx = 0
vy = 0
vz = 0

[particles]
source_term = ParticleUpdate_radiative_feedback

[star_feedback]
photon_rate = 1e49

[source_terms]
updates = CoolingUpdate_PRISM_hydro

[cooling]
data_path=/home/cphyc/Documents/prog/gizmo_rtz/data
ions=H_I,H_II,H2,He_I,He_II,He_III

[amr]
level_min=1
level_max=1

bx=15
by=15
bz=15

nbOctsPerGroup=2048
loadbalance_coherent_levels=2

markers_kernel=RefineCondition_pseudo_gradient
epsilon_refine=0.1
epsilon_coarsen=0.05

load_balancing_frequency=50
cycle_frequency=10

[mesh]
ndim=3

xmin=0.0
xmax=1.0

ymin=0.0
ymax=1.0

zmin=0.0
zmax=1.0

boundary_type_xmin=periodic
boundary_type_xmax=periodic

boundary_type_ymin=periodic
boundary_type_ymax=periodic

boundary_type_zmin=periodic
boundary_type_zmax=periodic

[hydro]
gamma0=1.666
riemann=hllc

[rad]
update=RadUpdate_euler_M1
c_rad=1 speedofLight

[output]
outputDir=./
outputPrefix=test_PRISM
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,xH_I,xH_II,xHe_I,xHe_II,xHe_III,e_rad,fx_rad,fy_rad,fz_rad

[units]
time = 1 Myr
length = 100 pc
density = 1 proton_mass/cm3
