[run]
tEnd=1.1819e-3
output_timeslice=1.1819e-6
initial_conditions = blast
passive_scalars_init = PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM,PRISM
n_passive_scalars = 23

[dt]
hydro_cfl=0.8
dt       = 1.0e-4

[blast]
density_in=1.0
density_out=1.2
radius=0.25

[amr]
level_min=2
level_max=5
nbOctsPerGroup=1024

markers_kernel=RefineCondition_pseudo_gradient
epsilon_coarsen=0.1
epsilon_refine=0.05

bx=4
by=4
bz=4

load_balancing_frequency=100
cycle_frequency=20

[mesh]
ndim=3

xmin=0.0
xmax=1.0

ymin=0.0
ymax=1.0

zmin=0.0
zmax=1.0

boundary_type_xmin=periodic
boundary_type_xmax=periodic
boundary_type_ymin=periodic
boundary_type_ymax=periodic
boundary_type_zmin=periodic
boundary_type_zmax=periodic

[hydro]
gamma0               = 1.6666666666666666666666
riemann              = hllc

[source_terms]
updates = CoolingUpdate_PRISM

[cooling]
UVB_tables = /home/cphyc/Documents/prog/gizmo_rtz/data/HM12/
charge_transfer_tables = /home/cphyc/Documents/prog/gizmo_rtz/data/charge_transfer/
high_temperature_metal_cooling_tables = /home/cphyc/Documents/prog/gizmo_rtz/data/high_T_cooling/
fine_structure_tables = /home/cphyc/Documents/prog/gizmo_rtz/data/fine_structure_data/
; ions = H_I, H_II, H2, He_I, He_II, He_III, C_I, C_II, C_III, C_IV, C_V, C_VI, N_I, N_II, N_III, N_IV, N_V, N_VI, N_VII, O_I, O_II, O_III, O_IV, O_V, O_VI, O_VII, O_VIII, Ne_I, Ne_II, Ne_III, Ne_IV, Ne_V, Ne_VI, Ne_VII, Ne_VIII, Ne_IX, Ne_X, Mg_I, Mg_II, Mg_III, Mg_IV, Mg_V, Mg_VI, Mg_VII, Mg_VIII, Mg_IX, Mg_X, Si_I, Si_II, Si_III, Si_IV, Si_V, Si_VI, Si_VII, Si_VIII, Si_IX, Si_X, Si_XI, S_I, S_II, S_III, S_IV, S_V, S_VI, S_VII, S_VIII, S_IX, S_X, S_XI, Fe_I, Fe_II, Fe_III, Fe_IV, Fe_V, Fe_VI, Fe_VII, Fe_VIII, Fe_IX, Fe_X, Fe_XI
ions = H_I, H_II, He_I, He_II, He_III, C_I, C_II, C_III, C_IV, C_V, C_VI, O_I, O_II, O_III, O_IV, O_V, O_VI, O_VII, O_VIII
initial_abundances = 1, 8.51e-2, 2.69e-4, 4.90e-4
initial_ionization = 0.0, 1.0, 0.0, 0.0, 1.0, 0., 0., 0., 0., 0., 1.0, 0, 0, 0, 0, 0, 0, 0, 1.0

[units]
; 10 pc in MKS
length = 3.08567758e+17
; 1 mp/cm**3 in MKS
density = 1.67262311e-21
; 846 Myr in MKS
time = 2.6699807254704036e+16
; Such that time**-2 * l**3 / m = 4 pi G = 1000


[output]
outputDir=./
outputPrefix=test_cooling
write_variables=rho,rho_vx,rho_vy,rho_vz,e_tot,passive_scalar_0,passive_scalar_1,passive_scalar_2,passive_scalar_3,passive_scalar_4,passive_scalar_5,passive_scalar_6,passive_scalar_7,passive_scalar_8,passive_scalar_9,passive_scalar_10,passive_scalar_11,passive_scalar_12,passive_scalar_13,passive_scalar_14,passive_scalar_15,passive_scalar_16,passive_scalar_17,passive_scalar_18,passive_scalar_19,passive_scalar_20,passive_scalar_21,passive_scalar_22
